### ISSUE TITLE
Model weight

### ISSUE THREAD

**Issue by Ning1208** [ngaggion/MultiCenterSegRepo#3]
This is really a great job, and we try to use this work. Thank you for providing the pre-training weight of the model, but we cannot open the corresponding link. We hope you can provide some help
![微信图片_20240418163752](https://github.com/ngaggion/MultiCenterSegRepo/assets/167415084/fa0190b7-c9ea-4df8-9ce9-7b7714122678)

**Comment by ngaggion** [comment]
Hello! 

Please check if it's fixed.

Best,
Nico

**Comment by Ning1208** [comment]
That's all right, thank you
